main = ".open-next/worker.js"
name = "63letters"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "63letters.com", custom_domain = true }
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"